Security start
qreqit/jv-spring-boot-web pull request #11
Opened 2024-07-17 18:27 UTC by qreqit

2024-07-18 18:16 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-18 18:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ex.getMessage());
```suggestion
        return ResponseEntity.status(HttpStatus.CONFLICT).body(ex.getMessage());
```

2024-07-18 18:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/mapper/UserMapper.java
> +@Mapper(componentModel = "spring")
```suggestion
@Mapper(componentModel = "spring",
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        injectionStrategy = InjectionStrategy.CONSTRUCTOR)
```

2024-07-18 18:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +@RequiredArgsConstructor
```suggestion
```

2024-07-18 18:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/service/impl/UserServiceImpl.java
> +        user.setEmail(requestDto.getEmail());
it should be mapper logic

2024-07-18 18:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(requestDto.getEmail())) {
```

2024-07-18 18:16 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/service/impl/UserServiceImpl.java
> +        if (!requestDto.getPassword().equals(requestDto.getRepeatPassword())) {
remove

2024-07-18 19:36 UTC, Elena-Bruyako requested changes
one comment

2024-07-18 19:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/service/impl/UserServiceImpl.java
> +        User user = new User();
```suggestion
        User user = userMapper.toUser(requestDto);
```

2024-07-19 06:53 UTC, Elena-Bruyako requested changes
see pr

2024-07-19 06:53 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/mapper/UserMapper.java
> +    User toUser(UserRegistrationRequestDto responseEntityExceptionHandler);
responseEntityExceptionHandler ???

2024-07-19 06:53 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("Can't register user");
add email to exception message

2024-07-19 06:54 UTC, qreqit commented on src/main/java/mate/academy/springbootwebgreqit/mapper/UserMapper.java
> +    User toUser(UserRegistrationRequestDto responseEntityExceptionHandler);
ohh

2024-07-19 06:59 UTC, Elena-Bruyako approved these changes

2024-08-16 08:23 UTC, merged