mvn compl
qreqit/jv-spring-boot-web pull request #12
Opened 2024-07-25 16:24 UTC by qreqit

2024-07-25 18:55 UTC, Elena-Bruyako requested changes
see comments

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/config/SecurityConfig.java
> +                .requestMatchers("/auth/registration", "/swagger-ui/**", "/v3/api-docs/**").permitAll()
```suggestion
                .requestMatchers(
                                        antMatcher("/auth/**"),
                                        antMatcher("/swagger-ui/**"),
                                        antMatcher("/v3/api-docs/**"))
                .permitAll()
                anyRequest()
               .authenticated()
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/config/SecurityConfig.java
> +            .authorizeHttpRequests(authorize -> authorize
```suggestion
            .cors(AbstractHttpConfigurer::disable)
            .csrf(AbstractHttpConfigurer::disable)
            .authorizeHttpRequests(authorize -> authorize
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/config/SecurityConfig.java
> +        return http.build();
```suggestion
            .sessionManagement(
                        s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .userDetailsService(service)
                .build();
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/controller/AdminController.java
> +    public String getAdminDashboard() {
did you see the tutorials from security module?

Pleasem check task description again and provide implementation according to it

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/controller/AdminController.java
> +public class AdminController {
```suggestion
@RequestMapping("/auth")
public class AuthenticationController {
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/Book.java
> +    @Column(name = "is_deleted")
```suggestion
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/Role.java
> +public abstract class Role implements GrantedAuthority {
```suggestion
public class Role implements GrantedAuthority {
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/Role.java
> +@Data
```suggestion
```

Add Table, get and set annotations

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/roles/RoleName.java
> +public enum RoleName {
you can create this enum in Role class

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/Role.java
> +    @Enumerated(EnumType.STRING)
Add required constraint

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +@Where(clause = "is_deleted = false")
`@Where` is deprecated

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +            name = "user_roles",
```suggestion
            name = "users_roles",
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +    private Set<Role> roles;
```suggestion
    private Set<Role> roles = new HashSet<>();
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +        return List.of();
```suggestion
        return roles;
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +        return UserDetails.super.isEnabled();
```suggestion
        return !isDeleted;
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +        return !isDeleted;
```suggestion
        return true;
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/repository/RoleRepository.java
> +public abstract class RoleRepository implements JpaRepository<Role, Long> {
abstract class repository?

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/security/CustomUserDetailService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Can't find user by email"));
use custom entity not found exception

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/security/CustomUserDetailService.java
> +        User user = userRepository.findByEmail(email)
```suggestion
        return userRepository.findByEmail(email)
```

2024-07-25 18:55 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-change-role.yaml
> +            tableName: user_roles
```suggestion
            tableName: users_roles
```

2024-07-26 07:31 UTC, Elena-Bruyako requested changes
see comments

2024-07-26 07:31 UTC, Elena-Bruyako commented on pom.xml
> +            <version>${spring-boot-starter-security.version}</version>
```suggestion
```

2024-07-26 07:31 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/config/SecurityConfig.java
> +@EnableMethodSecurity
```suggestion
@EnableMethodSecurity
@RequiredArgsConstructor
```

2024-07-26 07:31 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/config/SecurityConfig.java
> +    }
```suggestion
    private final UserDetailsService userDetailsService;
```

2024-07-26 07:31 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/controller/AuthenticationController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
Why did you make this changes?

2024-07-26 07:31 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/Role.java
> +@Entity
Add Table annotation

2024-07-26 07:31 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/User.java
> +        return List.of(new SimpleGrantedAuthority("ROLE_USER"));
```suggestion
        return roles;
```

2024-07-26 07:31 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-change-role.yaml
> +            tableName: user_roles
Not fixed

2024-07-26 07:49 UTC, qreqit commented on src/main/java/mate/academy/springbootwebgreqit/controller/AuthenticationController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
ohh, I made a mistake

2024-07-26 10:44 UTC, Elena-Bruyako requested changes
one comment

2024-07-26 10:44 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/model/Role.java
> +@Table
name ?

2024-07-30 11:37 UTC, Elena-Bruyako approved these changes

2024-08-16 08:28 UTC, merged