Add JWT Support
qreqit/jv-spring-boot-web pull request #13
Opened 2024-08-07 11:13 UTC by qreqit

2024-08-07 13:45 UTC, Elena-Bruyako requested changes
see comments

2024-08-07 13:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/controller/AuthenticationController.java
>      public UserResponseDto registerUser(@RequestBody UserRegistrationRequestDto requestBody) {
```suggestion
    public UserResponseDto register(@RequestBody @Valid UserRegistrationRequestDto requestBody) {
```

2024-08-07 13:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/controller/AuthenticationController.java
> +    public UserLoginResponseDto loginUser(@RequestBody UserLoginRequestDto response) {
```suggestion
    public UserLoginResponseDto login(@RequestBody @Valid UserLoginRequestDto response) {
```

2024-08-07 13:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-08-07 13:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_HEADER)) {
```

create constant for "Bearer "

2024-08-07 13:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(TOKEN_HEADER.length());
```

2024-08-07 13:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/springbootwebgreqit/dto/user/UserLoginResponseDto.java
> +@RequiredArgsConstructor
```suggestion
```

2024-08-08 14:35 UTC, okuzan approved these changes

2024-08-08 14:35 UTC, okuzan commented on src/main/java/mate/academy/springbootwebgreqit/security/JwtUtil.java
> +}
```suggestion
}

```

2024-08-16 08:29 UTC, merged